version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
      - ./:/var/www
    depends_on:
      - php
      - db

  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    user: ${CURRENT_UID}

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    container_name: db
    tty: true
    restart: unless-stopped
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql

  composer:
    container_name: composer
    image: composer:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - php
    user: ${CURRENT_UID}

  artisan:
    container_name: artisan
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    entrypoint: ['/var/www/artisan']
    depends_on:
      - db
    volumes:
      - ./:/var/www
    user: ${CURRENT_UID}

  npm:
    container_name: npm
    image: node:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ['npm']
    user: ${CURRENT_UID}
